require 'faker'
require 'bcrypt'
puts "🌱 Seeding Users..."
50.times do 
    User.create(first_name:Faker::Name.first_name,last_name: Faker::Name.last_name,password: BCrypt::Password.create(Faker::Bank.account_number), email: Faker::Internet.unique.email)
end

puts "🌱 Seeding Products..."
Product.create!(title: "Oculus Quest 2 — Advanced All-In-One Virtual Reality Headset — 256 GB",description: "Oculus quest 2 is our most advanced all-in-one VR system yet. Every detail has been engineered to make virtual worlds adapt to your movements, letting you explore awe-inspiring games and experiences with unparalleled freedom. No PC or Console required.",category: "Electronics",price: 399.0,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6494/6494866_rd.jpg")
Product.create!(title: "Motorola - Moto G Power (2022) 128GB (Unlocked) - Ice Blue",description: "With up to three days of battery life, moto g power lets you capture more without stopping to recharge. And with a 50 MP camera featuring Dual Capture, you can tell your story in more creative ways.",category: "Electronics",price: 249.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6494/6494854_sd.jpg")
Product.create!(title: "Insignia™ - 5 Qt. Analog Air Fryer - Stainless Steel",description: "Want to eat healthier without giving up the decadence of fried foods? The Insignia NS-AF5MSS2 5 Qt. Analog Air Fryer is your solution. By circulating hot air, this air fryer creates a crispy outer layer that locks in moisture.",category: "Electronics",price: 34.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6471/6471354_sd.jpg")
Product.create!(title: "Apple - AirPods Pro",description: "AirPods Pro feature Active Noise Cancellation for immersive sound. Transparency mode for hearing the world around you. They’re sweat and water resistant1 and have a customizable fit for all-day comfort.",category: "Electronics",price: 199.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4900/4900942_sd.jpg")
Product.create!(title: "Beats by Dr. Dre",description: "True wireless noise cancelling Beats Studio Bud are made for music. Designed with a custom acoustic platform, Beats Studio Bud are engineered to deliver powerful, balanced sound in a compact, in-ear form factor.",category: "Electronics",price: 119.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4900/4900915_sd.jpg")
Product.create!(title: "Apple Watch Series 7",description: "The largest, most advanced Always-on Retina display yet makes everything you do with your Apple Watch Series 7 bigger and better.",category: "Electronics",price: 399.0,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6215/6215932_sd.jpg")
Product.create!(title: "Apple Watch SE (GPS) 40mm Gold Aluminum Case with Pink",description: "Apple Watch SE has the same larger display size Retina display as Series 6, so you can see more at a glance. Advanced sensors to track all your fitness and workout goals. And powerful features to keep you healthy and safe.",category: "Electronics",price:279.0,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6215/6215914_sd.jpg")
Product.create!(title: "iRobot Roomba i6",description: "The Roomba i6 robot vacuum unleashes powerful cleaning when, where, and how you want with a single command to your Google Assistant or Alexa voice assistant.",category: "Electronics",price:349.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6477/6477037_sd.jpg")
Product.create!(title: "Apple - 10.2-Inch iPad",description: "Powerful. Easy to use. Versatile. The new iPad has a beautiful 10.2-inch Retina display, powerful A13 Bionic chip, an Ultra Wide front camera with Center Stage, and works with Apple Pencil and the Smart Keyboard.",category: "Electronics",price:329.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/4901/4901809_sd.jpg")
Product.create!(title: "Sony - PlayStation 5 Console",description: "The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio*, and an all-new generation of incredible PlayStation games.",category: "Electronics",price: 499.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6426/6426149_sd.jpg")
Product.create!(title: "Nespresso Vertuo Next Coffee Maker",description: "Nespresso introduces the VERTUO NEXT Glossy Black, the latest VERTUO Nespresso coffee maker with an all-new design in a limited edition color for the ultimate brewing experience.",category: "Electronics",price:159.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6483/6483539_sd.jpg")
Product.create!(title: "Bird Air Electric Scooter - Sonic Silver",description: "Bird Air Electric Scooter w/15.5 mi Max Operating Range & 15.5 mph Max Speed",category: "Electronics",price:499.99,image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6484/6484315_sd.jpg;maxHeight=640;maxWidth=550")
Product.create!(title: "Dyson - Supersonic Hair Dryer",description: "The new limited gift edition Dyson Supersonic hair dryer in fuchsia and nickel, with a Dyson-designed Prussian blue presentation case.",category: "Electronics",price: 429.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6496/6496496_sd.jpg")
Product.create!(title: "Nautilus - T618 Treadmill",description: "From the Nautilus Performance Series comes the T618 Treadmill. Designed for serious competitors looking to up their game, the T618 is fully loaded with dozens of training programs, Bluetooth connectivity and app-based tracking tools like the Explore the World App that help maximize motivation and power up performance.",category: "Electronics",price: 1299.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6405/6405081_sd.jpg")
Product.create!(title: "Hyperice - Hypervolt 2 Pro",description: "Get the same powerful percussion massage therapy that the world's best athletes have—right in the palm of your hand. Now with more power, and variable speeds, the Hypervolt 2 Pro Premium helps you recover faster so you can get back to doing more of what you love.",category: "Electronics",price: 399.99,image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6474/6474522_sd.jpg")
puts "🌱 Seeding Reviews..."
50.times do 
Review.create(content: Faker::Quote.famous_last_words, rating: Faker::Number.between(from: 1, to: 5),user_id: User.ids.sample,product_id: Product.ids.sample)
end

# Seed your database here

puts "✅ Done seeding!"
