default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ecom_development

test:
  <<: *default
  database: ecom_test

production:
  adapter: postgresql
  database: ecom_database #rename this to whatever you want
  username: username
  password: password
  host: localhost
